---
title: "ripper"
author: "Samuel Cardenete"
date: "4/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#Librerías a usar y funciones útiles:
library(dplyr)
library(Hmisc)
library(mice)
library(Amelia)
library(PerformanceAnalytics)
library(caret)

##FUNCIONES AUXILIARES:

# funcion para generar el archivo con el envio a kaggle. Argumentos:
# @param path ruta donde se quiere almacenar
# @param file nombre del archivo donde almacenar los datos
# @param cdataset conjunto de datos a almacenar
generarEnvio = function(y, file = "envio.csv", path = "./"){
  # se compone el path completo
  pathCompleto <- paste(path,file,sep="")
  
  # se escribe el archivo
  cat(paste("Id","Prediccion\n", sep = ","), file=pathCompleto)
  write.table(as.data.frame(cbind(1:length(y), y)), pathCompleto, sep = ",", row.names = FALSE, col.names = FALSE, append = TRUE)
}
```

## Preprocesamiento 
```{r, include=FALSE}
#lectura de datos:
train = read.csv("train.csv", na.string=c(" ", "NA", "?"))
test = read.csv("test.csv", na.string=c(" ", "NA", "?"))
#Pasamos a formato TIBBLE:
train = as_tibble(train)
test = as_tibble(test)
```
Técnicas preprocesamiento Ripper (...)


## Ripper

Generación de modelos RIPPER (...)

```{r}

```

