---
title: "Untitled"
author: "Carmen Biedma Rodriguez"
date: "25 de febrero de 2019"
output: pdf_document
---
#Modelo 8: desbalanceo


```{r}
library(dplyr)
library(Hmisc)
library(caret)
library(mice)
library(VIM)
library(class)
library(outliers)
library(ggplot2)
library(mvoutlier)
library(FSelector)
library(corrplot)
library(NoiseFiltersR)
library(lattice)
library(unbalanced)

source("../funcionesAux.R")

generarModelo <- function(train){
  control = trainControl(method="cv", number=5)
  model = caret::train(train[,-ncol(train)], train$C, method="knn",
                  metric="Accuracy", trControl=control,
                  tuneGrid = data.frame(.k = seq(1,21,2)))
  model
}
```


```{r}
datos <- read.csv("../train.csv",na.strings=c(" ","NA","?"))
test <- read.csv("../test.csv",na.strings=c(" ","NA","?"))

```


```{r}
d <- duplicated(datos)
length(which(d == TRUE))
datos <- datos[!d,]
```


```{r}
datosOutliersNA <- apply(datos[,1:(ncol(datos)-1)],2,function(c){
    cuartil.primero <- quantile(c,probs=0.25,na.rm = TRUE)
    cuartil.tercero <- quantile(c,probs=0.75,na.rm = TRUE)
    iqr <- cuartil.tercero - cuartil.primero
    extremo.inferior.outlier.normal <- cuartil.primero - 1.5*iqr
    extremo.superior.outlier.normal  <- cuartil.tercero + 1.5*iqr
    
    c[c<=extremo.inferior.outlier.normal] <- NA
    c[c>=extremo.superior.outlier.normal] <- NA
    c
})

datosOutliersNA <- as.data.frame(datosOutliersNA)
datosOutliersNA$C <- datos$C
```


```{r}
mice::md.pattern(datosOutliersNA,plot=TRUE)
```


```{r}
completos <- mice::ncc(datosOutliersNA)
incompletos <- mice::nic(datosOutliersNA)
cat("Datos completos: ",completos, " e incompletos: ",incompletos,"\n")
imputados <- mice::mice(datosOutliersNA, m=5, meth="pmm")
datosImputados <- mice::complete(imputados)
completos <- mice::ncc(datosImputados)
incompletos <- mice::nic(datosImputados)
cat("Datos completos: ",completos, " e incompletos: ",incompletos,"\n")
datosOutliersNA.imputadosPMM <- datosImputados
```

```{r}
datosOutliersNA.imputadosPMM$C <- as.factor(datosOutliersNA.imputadosPMM$C)
out <- IPF(C~., data = datosOutliersNA.imputadosPMM ,s = 3)
summary(out, explicit =TRUE)
out$cleanData
datosOutliersNA.imputadosPMM.IPF <- datosOutliersNA.imputadosPMM[setdiff(1:nrow(datosOutliersNA.imputadosPMM),out$remIdx),]
```

```{r}
table(datosOutliersNA.imputadosPMM.IPF$C)
balanced <- ubTomek(datosOutliersNA.imputadosPMM.IPF[,-ncol(datosOutliersNA.imputadosPMM.IPF)],datosOutliersNA.imputadosPMM.IPF$C)

datosOutliersNA.imputadosPMM.IPF.Tomek1 <- balanced$X
datosOutliersNA.imputadosPMM.IPF.Tomek1$C <- balanced$Y
table(datosOutliersNA.imputadosPMM.IPF.Tomek1$C)

balanced <- ubTomek(datosOutliersNA.imputadosPMM.IPF.Tomek1[,-ncol(datosOutliersNA.imputadosPMM.IPF.Tomek1)],datosOutliersNA.imputadosPMM.IPF.Tomek1$C)

datosOutliersNA.imputadosPMM.IPF.Tomek2 <- balanced$X
datosOutliersNA.imputadosPMM.IPF.Tomek2$C <- balanced$Y
table(datosOutliersNA.imputadosPMM.IPF.Tomek2$C)
```

```{r}
datosPrep <- caret::preProcess(datosOutliersNA.imputadosPMM.IPF.Tomek2[,-ncol(datosOutliersNA.imputadosPMM.IPF.Tomek2)],method = c("center","scale"))
datosOutliersNA.imputadosPMM.IPF.Tomek2[,-ncol(datosOutliersNA.imputadosPMM.IPF.Tomek2)] <- predict(datosPrep,datosOutliersNA.imputadosPMM.IPF.Tomek2[,-ncol(datosOutliersNA.imputadosPMM.IPF.Tomek2)])
datosPrep <- caret::preProcess(test,method = c("center","scale"))
test.prep <- predict(datosPrep,test)
```

```{r}
datosOutliersNA.imputadosPMM.IPF.Tomek2$C <- as.factor(datosOutliersNA.imputadosPMM.IPF.Tomek2$C)
model <- generarModelo(datosOutliersNA.imputadosPMM.IPF.Tomek2)
model
```


```{r}
test_pred <- predict(model,test)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioDefinitivo8.csv")
```






















```{r}
m <- cor(datosOutliersNA.imputadosPMM.IPF.Tomek2[,-ncol(datosOutliersNA.imputadosPMM.IPF.Tomek2)])
correlados <- findCorrelation(m, cutoff = 0.8)
correlados
datosOutliersNA.imputadosPMM.IPF.Tomek2.cor <- datosOutliersNA.imputadosPMM.IPF.Tomek2[,-correlados]
test.cor <- test[,-correlados]
```

```{r}
datosOutliersNA.imputadosPMM.IPF.Tomek2.cor$C <- as.factor(datosOutliersNA.imputadosPMM.IPF.Tomek2.cor$C)
model <- generarModelo(datosOutliersNA.imputadosPMM.IPF.Tomek2.cor)
model
```


```{r}
test_pred <- predict(model,test)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioDefinitivo9.csv")
```




#Envio último dia 1: imputacion,ruido y tomek

```{r}
datos <- read.csv("../train.csv",na.strings=c(" ","NA","?"))
test <- read.csv("../test.csv",na.strings=c(" ","NA","?"))
```


```{r}
imputados.amelia <- Amelia::amelia(datos,m=1,parallel="multicore",noms="C")
incompletos.amelia <- mice::nic(imputados.amelia$imputations$imp1)
completos.amelia <- mice::ncc(imputados.amelia$imputations$imp1)
cat("COMPLETOS = ", completos.amelia, " INCOMPLETOS = ",incompletos.amelia)
impAmelia <- imputados.amelia$imputations$imp1
```

```{r}
impAmelia$C <- as.factor(impAmelia$C)
out <- IPF(C~., data = impAmelia ,s = 3)
summary(out, explicit =TRUE)
out$cleanData
impAmelia.IPF <- impAmelia[setdiff(1:nrow(impAmelia),out$remIdx),]
```


```{r}
impAmelia.IPF$C <- as.factor(impAmelia.IPF$C)
model <- generarModelo(impAmelia.IPF)
model
```



```{r}
table(impAmelia.IPF$C)
balanced <- ubTomek(impAmelia.IPF[,-ncol(impAmelia.IPF)],impAmelia.IPF$C)

impAmelia.IPF.Tomek1 <- balanced$X
impAmelia.IPF.Tomek1$C <- balanced$Y
table(impAmelia.IPF.Tomek1$C)

balanced <- ubTomek(impAmelia.IPF.Tomek1[,-ncol(impAmelia.IPF.Tomek1)],impAmelia.IPF.Tomek1$C)

impAmelia.IPF.Tomek2 <- balanced$X
impAmelia.IPF.Tomek2$C <- balanced$Y
table(impAmelia.IPF.Tomek2$C)
```

```{r}
impAmelia.IPF.Tomek2$C <- as.factor(impAmelia.IPF.Tomek2$C)
model <- generarModelo(impAmelia.IPF.Tomek2)
model
```


```{r}
datosPrep <- preProcess(impAmelia.IPF.Tomek2[,-ncol(impAmelia.IPF.Tomek2)], c("center", "scale"))
impAmelia.IPF.Tomek2.norm <- predict(datosPrep, impAmelia.IPF.Tomek2)
test.norm <- predict(datosPrep,test)
```



```{r}
impAmelia.IPF.Tomek2.norm$C <- as.factor(impAmelia.IPF.Tomek2.norm$C)
model <- generarModelo(impAmelia.IPF.Tomek2.norm)
model
```

```{r}
test_pred <- predict(model,test.norm)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioFinal1.csv")
```


#ENVIO FINAL 2: Normalizar antes de hacer nada

```{r}
datos <- read.csv("../train.csv",na.strings=c(" ","NA","?"))
test <- read.csv("../test.csv",na.strings=c(" ","NA","?"))
```


```{r}
imputados.amelia <- Amelia::amelia(datos,m=1,parallel="multicore",noms="C")
incompletos.amelia <- mice::nic(imputados.amelia$imputations$imp1)
completos.amelia <- mice::ncc(imputados.amelia$imputations$imp1)
cat("COMPLETOS = ", completos.amelia, " INCOMPLETOS = ",incompletos.amelia)
impAmelia <- imputados.amelia$imputations$imp1
```

```{r}
datosPrep <- preProcess(impAmelia[,-ncol(impAmelia)], c("center", "scale"))
impAmelia.norm <- predict(datosPrep, impAmelia)
test.norm <- predict(datosPrep,test)
```

```{r}
impAmelia.norm$C <- as.factor(impAmelia.norm$C)
model <- generarModelo(impAmelia.norm)
model
```



```{r}
test_pred <- predict(model,test.norm)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioFinal2.csv")
```

```{r}
table(impAmelia.norm$C)
balanced <- ubTomek(impAmelia.norm[,-ncol(impAmelia.norm)],impAmelia.norm$C)

impAmelia.norm.Tomek1 <- balanced$X
impAmelia.norm.Tomek1$C <- balanced$Y
table(impAmelia.norm.Tomek1$C)

balanced <- ubTomek(impAmelia.norm.Tomek1[,-ncol(impAmelia.norm.Tomek1)],impAmelia.norm.Tomek1$C)

impAmelia.norm.Tomek2 <- balanced$X
impAmelia.norm.Tomek2$C <- balanced$Y
table(impAmelia.norm.Tomek2$C)
```

```{r}
impAmelia.norm.Tomek2$C <- as.factor(impAmelia.norm.Tomek2$C)
model <- generarModelo(impAmelia.norm.Tomek2)
model
```

```{r}
test_pred <- predict(model,test.norm)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioFinal3.csv")
```

#Envio final 4: no hacer tomek, imputar, normalizar y ruido

```{r}
datos <- read.csv("../train.csv",na.strings=c(" ","NA","?"))
test <- read.csv("../test.csv",na.strings=c(" ","NA","?"))
```


```{r}
imputados.amelia <- Amelia::amelia(datos,m=1,parallel="multicore",noms="C")
incompletos.amelia <- mice::nic(imputados.amelia$imputations$imp1)
completos.amelia <- mice::ncc(imputados.amelia$imputations$imp1)
cat("COMPLETOS = ", completos.amelia, " INCOMPLETOS = ",incompletos.amelia)
impAmelia <- imputados.amelia$imputations$imp1
```

```{r}
datosPrep <- preProcess(impAmelia[,-ncol(impAmelia)], c("center", "scale"))
impAmelia.norm <- predict(datosPrep, impAmelia)
test.norm <- predict(datosPrep,test)
```

```{r}
impAmelia.norm$C <- as.factor(impAmelia.norm$C)
out <- IPF(C~., data = impAmelia.norm ,s = 3)
impAmelia.norm.IPF <- out$cleanData
```

```{r}
impAmelia.norm.IPF$C <- as.factor(impAmelia.norm.IPF$C)
model <- generarModelo(impAmelia.norm.IPF)
model
```


```{r}
test_pred <- predict(model,test.norm)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioFinal4.csv")
```


Añadimos tomek

```{r}
table(impAmelia.norm.IPF$C)
balanced <- ubTomek(impAmelia.norm.IPF[,-ncol(impAmelia.norm.IPF)],impAmelia.norm.IPF$C)

impAmelia.norm.IPF.Tomek1 <- balanced$X
impAmelia.norm.IPF.Tomek1$C <- balanced$Y
table(impAmelia.norm.IPF.Tomek1$C)

```


```{r}
impAmelia.norm.IPF.Tomek1$C <- as.factor(impAmelia.norm.IPF.Tomek1$C)
model <- generarModelo(impAmelia.norm.IPF.Tomek1)
model
```


```{r}
balanced <- ubTomek(impAmelia.norm.IPF.Tomek1[,-ncol(impAmelia.norm.IPF.Tomek1)],impAmelia.norm.IPF.Tomek1$C)

impAmelia.norm.IPF.Tomek2 <- balanced$X
impAmelia.norm.IPF.Tomek2$C <- balanced$Y
table(impAmelia.norm.IPF.Tomek2$C)
```

```{r}
impAmelia.norm.IPF.Tomek2$C <- as.factor(impAmelia.norm.IPF.Tomek2$C)
model <- generarModelo(impAmelia.norm.IPF.Tomek2)
model
```



```{r}
test_pred <- predict(model,test.norm)
test_pred
```

```{r}
generarEnvio(y=test_pred,file="envioFinal5.csv")
```

Outliers

```{r}
datosOutliersNA <- apply(impAmelia.norm.IPF.Tomek2[,1:(ncol(datos)-1)],2,function(c){
    cuartil.primero <- quantile(c,probs=0.25,na.rm = TRUE)
    cuartil.tercero <- quantile(c,probs=0.75,na.rm = TRUE)
    iqr <- cuartil.tercero - cuartil.primero
    extremo.inferior.outlier.normal <- cuartil.primero - 1.5*iqr
    extremo.superior.outlier.normal  <- cuartil.tercero + 1.5*iqr
    
    c[c<=extremo.inferior.outlier.normal] <- NA
    c[c>=extremo.superior.outlier.normal] <- NA
    c
})

datosOutliersNA <- as.data.frame(datosOutliersNA)
datosOutliersNA$C <- impAmelia.norm.IPF.Tomek2$C
```

```{r}
imputados.amelia <- Amelia::amelia(datosOutliersNA,m=1,parallel="multicore",noms="C")
incompletos.amelia <- mice::nic(imputados.amelia$imputations$imp1)
completos.amelia <- mice::ncc(imputados.amelia$imputations$imp1)
cat("COMPLETOS = ", completos.amelia, " INCOMPLETOS = ",incompletos.amelia)
impAmelia.outliersNa <- imputados.amelia$imputations$imp1
```


```{r}
impAmelia.outliersNa$C <- as.factor(impAmelia.outliersNa$C)
model <- generarModelo(impAmelia.outliersNa)
model
```


```{r}
completos <- mice::ncc(datosOutliersNA)
incompletos <- mice::nic(datosOutliersNA)
cat("Datos completos: ",completos, " e incompletos: ",incompletos,"\n")
imputados <- mice::mice(datosOutliersNA, m=5, meth="pmm")
pmm.outliersNa <- mice::complete(imputados)
completos <- mice::ncc(pmm.outliersNa)
incompletos <- mice::nic(pmm.outliersNa)
cat("Datos completos: ",completos, " e incompletos: ",incompletos,"\n")
```

```{r}
pmm.outliersNa$C <- as.factor(pmm.outliersNa$C)
model <- generarModelo(pmm.outliersNa)
model
```